### PR TITLE
Factor out types

### PR DESCRIPTION
**Pull request by codalogic**
As a good house keeping activity it seems worth factoring out the repetition of the basic value | object | array types

### CODE REVIEW

**Comment by codalogic** [comment]
P.S. This builds on Pull Request #2 (Make Target rule name more explicit) as it affects many of the same code lines, and if the changes were against master it would just result in merge conflicts.

**Comment by anewton1998** [comment]
dang it. I should have merged this one instead of #2.

**Comment by codalogic** [comment]
If it's causing trouble I'll re-create it off the latest branch

**Comment by anewton1998** [comment]
No problem. Already fixed the conflict.

**Comment by codalogic** [comment]
Awesome.  Thanks.

**Pull request merged**
